version: '2'
services:
    client:
        build: 
            context: ../uscope_react
            dockerfile: ./Dockerfile
        image: client:latest
        stdin_open: true
        tty: true
        networks: 
            - external_network
        ports:
            - 3004:3004
        volumes: 
            - /home/fils/git/uscope_react:/uscope_client
    server:
        build: ./server
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 8989:8989
        volumes: 
            - /home/fils/git/uscope_server:/server
    redis:
        build: ./redis
        image: redis:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 6379:6379
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge
