version: '2'
services:
    client:
        build: 
            context: ../uscope_react
            dockerfile: ./Dockerfile
        image: client:latest
        networks: 
            - external_network
        depends_on:
            - server
        ports:
            - 80:80
            - 443:443
            - 3004:3004
        volumes: 
            - /home/root/uscope/uscope_react:/uscope_client
    server:
        build: ./server
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 8989:8989
        depends_on:
            database:
                condition: service_healthy
        volumes: 
            - /home/root/uscope/uscope_server:/server
    database:
        build: ./database
        image: database:latest
        networks:
            - internal_network
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=test
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 5s
            retries: 10
    driver:
        build:
            context: ../uscope_driver
            dockerfile: ./Dockerfile
        image: driver:latest
        ports:
            - 6666:6666
        networks:
            - internal_network
        privileged: true
        volumes: 
            - /lib/firmware:/lib/firmware
            - /sys/class/fpga_manager:/sys/class/fpga_manager
            - /dev/uscope_BUS_0:/dev/uscope_BUS_0
            - /dev/uscope_BUS_1:/dev/uscope_BUS_1
            - /dev/uscope_data:/dev/uscope_data
            - /dev/mem:/dev/mem
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge

        
