version: '2'
services:
    client:
        build: 
            context: ../uscope_react
            dockerfile: ./Dockerfile
        image: client:latest
        stdin_open: true
        tty: true
        networks: 
            - external_network
        ports:
            - 8002:80
            - 3004:3004
        volumes: 
            - /home/root/uscope/uscope_react:/uscope_client
    server:
        build: ./server
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 8989:8989
            
        volumes: 
            - /home/root/uscope/uscope_server:/server
    redis:
        build: ./redis
        image: redis:latest
        networks:
            - internal_network
        ports:
            - 6379:6379
    driver:
        build:
            context: ../uscope_driver
            dockerfile: ./Dockerfile
        image: driver:latest
        ports:
            - 6666:6666
        networks:
            - internal_network
        volumes:
            - /lib/firmware:/lib/firmware
            - /sys/class/fpga_manager:/sys/class/fpga_manager
            - /dev/uio0:/dev/uio0
            - /dev/mem:/dev/mem
        privileged: true
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge

        
