version: '2'
services:
    client:
        image: client:latest
        stdin_open: true
        tty: true
        depends_on:
            - server
        networks: 
            - external_network
        ports:
            - 80:80
            - 443:443
            - 3004:3004
    server:
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 8989:8989
    redis:
        image: redis:latest
        networks:
            - internal_network
            - external_network
    database:
        image: database:latest
        networks:
            - internal_network
            - external_network
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=test
    driver:
        image: driver:latest
        ports:
            - 6666:6666
        networks:
            - internal_network
        privileged: true
        command: ["/driver/uscope_driver", "--debug", "--log"]
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge

        
