version: '3'
services:
    client:
        image: client:latest
        networks: 
            - external_network
        depends_on:
            - server
        ports:
            - 80:80
            - 443:443
            - 3004:3004
    server:
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            
            - internal_network
            - external_network
        volumes: 
            - /lib/firmware:/lib/firmware
        ports:
            - 8989:8989
    redis:
        image: redis:latest
        networks:
            - internal_network
    database:
        image: database:latest
        networks:
            - internal_network
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=test
    driver:
        image: driver:latest
        ports:
            - 6666:6666
        networks:
            - internal_network
        privileged: true
        volumes: 
            - /lib/firmware:/lib/firmware
            - /sys/class/fpga_manager:/sys/class/fpga_manager
            - /dev/uscope_BUS_0:/dev/uscope_BUS_0
            - /dev/uscope_BUS_1:/dev/uscope_BUS_1
            - /dev/uscope_data:/dev/uscope_data
            - /dev/mem:/dev/mem
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge

        
