version: '2'
services:
    client:
        build: 
            context: ../uscope_react
            dockerfile: ./Dockerfile
        image: client:latest
        stdin_open: true
        tty: true
        networks: 
            - external_network
        ports:
            - 80:80
            - 443:443
            - 3004:3004
        volumes: 
            - /home/fils/git/uscope_react:/uscope_client
    server:
        build: ./server
        stdin_open: true
        tty: true
        image: server:latest
        networks:
            - internal_network
            - external_network
        ports:
            - 8989:8989
            
        volumes: 
            - /home/fils/git/uscope_server:/server
    database:
        build: ./database
        networks:
            - internal_network
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=test
    driver:
        build:
            context: ../uscope_driver
            dockerfile: ./Dockerfile
        image: driver:latest
        ports:
            - 6666:6666
        networks:
            - internal_network
        privileged: true
networks:
    internal_network:
        driver: bridge
        internal: true
    external_network:
        driver: bridge

        
