- hosts: uzed
  remote_user: root
  tasks:

########################################################
#             PREPARE HOST ENVIRONMENT                 #
########################################################

    - name: Extend root partition
      parted:
        device: /dev/mmcblk0
        number: 2
        part_end: "100%"
        resize: true
        state: present
    
    - name: Grow root filesystem
      command: resize2fs /dev/mmcblk0p2

    - name: Reboot (Refresh kernel partition table)
      reboot: