- hosts: localhost
  vars:
    toolchain_target_dir: /software/yocto_ansible
    xilinx_tools_release: rel-v2020.2
  tasks:

########################################################
#             DOWNLOAD AND SETUP YOCTO                 #
########################################################

  - name: Create directory for yocto toolchain
    file:
      path: "{{toolchain_target_dir}}"
      state: directory

  - name: Download repo tool
    get_url:
      url: https://storage.googleapis.com/git-repo-downloads/repo
      dest: "{{toolchain_target_dir}}"

  - name: Make repo binary executable
    file: 
      path: "{{toolchain_target_dir + '/repo'}}"
      mode: a+x

  - name: Setup directory structure with yocto and xilinx layers
    command: 
    args:
      cmd: "{{toolchain_target_dir + '/repo'}} init -u git://github.com/Xilinx/yocto-manifests.git -b '{{xilinx_tools_release}}'"
      chdir: "{{toolchain_target_dir}}"

  - name: Download Base repositories
    command: 
    args:
      cmd: "{{toolchain_target_dir + '/repo'}} sync"
      chdir: "{{toolchain_target_dir}}"
  
  - name: Checkout Base repositories
    command: 
    args:
      cmd: "{{toolchain_target_dir + '/repo'}} start {{xilinx_tools_release}} --all"
      chdir: "{{toolchain_target_dir}}"

  - name: Clone meta-uscope layer
    git:
      repo: git@github.com:filssavi/meta-uscope.git
      dest: "{{toolchain_target_dir+'/sources/meta-uscope'}}"
      accept_hostkey: yes

  - name: Copy meta-xilinx patch
    copy:
      src: meta-xilinx.patch
      dest: "{{toolchain_target_dir+'/sources/meta-xilinx'}}"

  - name: Apply microzed patch to meta-xilinx
    command:
      cmd: git apply meta-xilinx.patch
      chdir: "{{toolchain_target_dir+'/sources/meta-xilinx'}}"
  
  - name: Remove meta-xilinx patch
    file:
      path: "{{toolchain_target_dir+'/sources/meta-xilinx/meta-xilinx.patch'}}"
      state: absent

  - name: Add meta-uscope layer to bblayers
    shell: 
    args:
      cmd: "source {{toolchain_target_dir+'/setupsdk' }} && bitbake-layers add-layer {{toolchain_target_dir+'/sources/meta-uscope'}}"
      chdir: "{{toolchain_target_dir}}"
      executable: /bin/bash

  - name: Copy local.conf
    copy:
      src: local.conf
      dest: "{{toolchain_target_dir+'/build/conf'}}"
